/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ArIndexRouteImport } from './routes/ar.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ProductHandleRouteImport } from './routes/product/$handle'
import { Route as ArJournalIndexRouteImport } from './routes/ar.journal.index'
import { Route as ArJournalSlugRouteImport } from './routes/ar.journal.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/ar/',
  path: '/ar/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ArJournalIndexRoute = ArJournalIndexRouteImport.update({
  id: '/ar/journal/',
  path: '/ar/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArJournalSlugRoute = ArJournalSlugRouteImport.update({
  id: '/ar/journal/$slug',
  path: '/ar/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/orders': typeof OrdersRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/ar/': typeof ArIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/ar/journal/$slug': typeof ArJournalSlugRoute
  '/ar/journal/': typeof ArJournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/orders': typeof OrdersRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/ar': typeof ArIndexRoute
  '/journal': typeof JournalIndexRoute
  '/ar/journal/$slug': typeof ArJournalSlugRoute
  '/ar/journal': typeof ArJournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/orders': typeof OrdersRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/ar/': typeof ArIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/ar/journal/$slug': typeof ArJournalSlugRoute
  '/ar/journal/': typeof ArJournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/orders'
    | '/journal/$slug'
    | '/product/$handle'
    | '/ar/'
    | '/journal/'
    | '/ar/journal/$slug'
    | '/ar/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/orders'
    | '/journal/$slug'
    | '/product/$handle'
    | '/ar'
    | '/journal'
    | '/ar/journal/$slug'
    | '/ar/journal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/orders'
    | '/journal/$slug'
    | '/product/$handle'
    | '/ar/'
    | '/journal/'
    | '/ar/journal/$slug'
    | '/ar/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  OrdersRoute: typeof OrdersRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ArIndexRoute: typeof ArIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ArJournalSlugRoute: typeof ArJournalSlugRoute
  ArJournalIndexRoute: typeof ArJournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/ar'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/journal/': {
      id: '/ar/journal/'
      path: '/ar/journal'
      fullPath: '/ar/journal/'
      preLoaderRoute: typeof ArJournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/journal/$slug': {
      id: '/ar/journal/$slug'
      path: '/ar/journal/$slug'
      fullPath: '/ar/journal/$slug'
      preLoaderRoute: typeof ArJournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  OrdersRoute: OrdersRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  ArIndexRoute: ArIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  ArJournalSlugRoute: ArJournalSlugRoute,
  ArJournalIndexRoute: ArJournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
